"""Migration

Revision ID: 01972705db21
Revises: 22d1ed03d648
Create Date: 2023-08-11 17:44:21.304020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01972705db21'
down_revision = '22d1ed03d648'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
