"""Migration

Revision ID: 021c164c16cf
Revises: 4c22f1bf9677
Create Date: 2023-08-05 20:00:40.653625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021c164c16cf'
down_revision = '4c22f1bf9677'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
