"""Add UC to Likes

Revision ID: 022c66861539
Revises: c746a8eb1f96
Create Date: 2023-07-09 01:29:34.548081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022c66861539'
down_revision = 'c746a8eb1f96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_user_uc', 'likes', ['post_id', 'user'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_user_uc', 'likes', type_='unique')
    # ### end Alembic commands ###
