"""Migration

Revision ID: 04c7f9b1a34e
Revises: e6f606396f24
Create Date: 2023-08-11 19:08:33.721956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c7f9b1a34e'
down_revision = 'e6f606396f24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
