"""Migration

Revision ID: 0796bb871207
Revises: 0ef648f442d6
Create Date: 2023-08-11 19:05:53.141946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0796bb871207'
down_revision = '0ef648f442d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
