"""Migration

Revision ID: 0b0dfd832351
Revises: cd0775648dcf
Create Date: 2023-08-08 21:04:33.561498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0dfd832351'
down_revision = 'cd0775648dcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
