"""Migration

Revision ID: 0dbe86680beb
Revises: a3cdaf99693d
Create Date: 2023-08-09 20:35:40.088814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbe86680beb'
down_revision = 'a3cdaf99693d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
