"""Migration

Revision ID: 0e527153bf41
Revises: f47b1990148d
Create Date: 2023-08-18 19:11:36.682103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e527153bf41'
down_revision = 'f47b1990148d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
