"""Migration

Revision ID: 10b7bd2ecaeb
Revises: 608cbe0faf9f
Create Date: 2023-08-11 19:03:58.634677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b7bd2ecaeb'
down_revision = '608cbe0faf9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
