"""Migration

Revision ID: 1126506b30ad
Revises: 86f066c18561
Create Date: 2023-08-08 20:33:08.729364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1126506b30ad'
down_revision = '86f066c18561'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
