"""Migration

Revision ID: 11547c28cbf9
Revises: f4160ee874b5
Create Date: 2023-08-18 20:05:11.410408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11547c28cbf9'
down_revision = 'f4160ee874b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
