"""Migration

Revision ID: 11895eca851e
Revises: a8cd28f6285e
Create Date: 2023-08-18 20:02:35.578796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11895eca851e'
down_revision = 'a8cd28f6285e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
