"""Add Comments Table

Revision ID: 12d03a383fba
Revises: c87511b9ff7c
Create Date: 2023-07-10 00:17:34.055739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d03a383fba'
down_revision = 'c87511b9ff7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
