"""Test try

Revision ID: 12d1a51b8e19
Revises: 4ae75b435dcb
Create Date: 2023-07-31 23:43:35.358433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d1a51b8e19'
down_revision = '4ae75b435dcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
