"""Migration

Revision ID: 1982f97b12ca
Revises: a01e05e4a50d
Create Date: 2023-08-08 20:32:47.035468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1982f97b12ca'
down_revision = 'a01e05e4a50d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
