"""Migration

Revision ID: 198dcaeeb1fc
Revises: 0796bb871207
Create Date: 2023-08-11 19:06:15.934342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198dcaeeb1fc'
down_revision = '0796bb871207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
