"""Migration

Revision ID: 1a155e29faa9
Revises: b5789fb7fdcd
Create Date: 2023-08-18 18:12:57.871101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a155e29faa9'
down_revision = 'b5789fb7fdcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
