"""Test db

Revision ID: 1c5159b8cf8b
Revises: 371f0bff4f48
Create Date: 2023-08-01 23:29:17.667110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5159b8cf8b'
down_revision = '371f0bff4f48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
