"""Migration

Revision ID: 20d0373c1787
Revises: 4afdcbcfb817
Create Date: 2023-08-08 18:08:29.381091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d0373c1787'
down_revision = '4afdcbcfb817'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
