"""Migration

Revision ID: 22d1ed03d648
Revises: ca55c14dd6a1
Create Date: 2023-08-11 17:43:58.505663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d1ed03d648'
down_revision = 'ca55c14dd6a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
