"""Migration

Revision ID: 2481f5f3c047
Revises: 69fdfe9baca9
Create Date: 2023-08-09 18:14:25.039940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2481f5f3c047'
down_revision = '69fdfe9baca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
