"""Simple migration

Revision ID: 254694923bf5
Revises: ee01f6d1553b
Create Date: 2023-08-01 23:35:24.848534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254694923bf5'
down_revision = 'ee01f6d1553b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
