"""Migration

Revision ID: 28151541c60f
Revises: 7ce91608ad7a
Create Date: 2023-08-18 19:39:19.131827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28151541c60f'
down_revision = '7ce91608ad7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
