"""Migration

Revision ID: 29ee1cebf326
Revises: be4881b23bb7
Create Date: 2023-08-18 18:11:25.029570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ee1cebf326'
down_revision = 'be4881b23bb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
