"""Add UC to Favourites

Revision ID: 2a6464ede3ac
Revises: 572769595647
Create Date: 2023-07-24 21:44:13.876382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6464ede3ac'
down_revision = '572769595647'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_user_uc_favourites', 'favourites', ['post_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_user_uc_favourites', 'favourites', type_='unique')
    # ### end Alembic commands ###
