"""Changing Enum to String

Revision ID: 2a868e4e4b9d
Revises: 9b2f49d4593b
Create Date: 2023-07-08 00:57:07.803196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a868e4e4b9d'
down_revision = '9b2f49d4593b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
