"""Migration

Revision ID: 2abea64a8d31
Revises: 28151541c60f
Create Date: 2023-08-18 20:01:02.799157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abea64a8d31'
down_revision = '28151541c60f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
