"""Migration

Revision ID: 3475413e4f68
Revises: 9e212eace932
Create Date: 2023-08-18 18:45:47.227631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3475413e4f68'
down_revision = '9e212eace932'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
