"""Migration

Revision ID: 36f30816bca8
Revises: e8a58a65dec2
Create Date: 2023-08-15 19:05:34.541770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f30816bca8'
down_revision = 'e8a58a65dec2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
