"""Test db

Revision ID: 371f0bff4f48
Revises: 614aefe09543
Create Date: 2023-08-01 23:28:32.810591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371f0bff4f48'
down_revision = '614aefe09543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
