"""Migration

Revision ID: 411066d7967e
Revises: 658dc7194e53
Create Date: 2023-08-11 17:45:24.775915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411066d7967e'
down_revision = '658dc7194e53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
