"""Migration

Revision ID: 41dd939c7a7c
Revises: fa0869c6d860
Create Date: 2023-08-09 20:36:25.070552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dd939c7a7c'
down_revision = 'fa0869c6d860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
