"""Migration

Revision ID: 43b9fa926a71
Revises: 7c81acdf07dd
Create Date: 2023-08-18 19:12:54.927387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b9fa926a71'
down_revision = '7c81acdf07dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
