"""Migration

Revision ID: 445239fdfa44
Revises: e8ac5e8618a5
Create Date: 2023-08-12 17:38:35.451890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445239fdfa44'
down_revision = 'e8ac5e8618a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
