"""Migration

Revision ID: 45195af5974f
Revises: 7a7b2e2eaf7d
Create Date: 2023-08-08 18:25:15.023578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45195af5974f'
down_revision = '7a7b2e2eaf7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
