"""Migration

Revision ID: 45a7a29cc863
Revises: 75ad7443640d
Create Date: 2023-08-08 20:33:31.536592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a7a29cc863'
down_revision = '75ad7443640d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
