"""Migration

Revision ID: 45fe6a1196af
Revises: d30301b66dea
Create Date: 2023-08-18 19:10:58.866479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fe6a1196af'
down_revision = 'd30301b66dea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
