"""Migration

Revision ID: 4605e07e7ad6
Revises: 198dcaeeb1fc
Create Date: 2023-08-11 19:06:37.397275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4605e07e7ad6'
down_revision = '198dcaeeb1fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
