"""Add complaint

Revision ID: 472e901135aa
Revises: 5d3e5b98bc94
Create Date: 2023-07-05 00:21:53.219733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472e901135aa'
down_revision = '5d3e5b98bc94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('user', sa.String(), nullable=True))
    op.drop_constraint('complaints_username_fkey', 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'users', ['user'], ['username'], ondelete='cascade')
    op.drop_column('complaints', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key('complaints_username_fkey', 'complaints', 'users', ['username'], ['username'], ondelete='CASCADE')
    op.drop_column('complaints', 'user')
    # ### end Alembic commands ###
