"""Migration

Revision ID: 49b48b8fbc02
Revises: aa8596920f21
Create Date: 2023-08-09 19:48:59.008070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b48b8fbc02'
down_revision = 'aa8596920f21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
