"""Add BL table

Revision ID: 4ae75b435dcb
Revises: 2a6464ede3ac
Create Date: 2023-07-25 01:27:03.620741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae75b435dcb'
down_revision = '2a6464ede3ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'user_id', name='username_user_id_uc')
    )
    op.create_index(op.f('ix_black_list_id'), 'black_list', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_black_list_id'), table_name='black_list')
    op.drop_table('black_list')
    # ### end Alembic commands ###
