"""Migration

Revision ID: 4afdcbcfb817
Revises: b419722428ff
Create Date: 2023-08-08 18:08:18.858478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afdcbcfb817'
down_revision = 'b419722428ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
