"""Migration

Revision ID: 506520e7e4b4
Revises: fc1120bdb66f
Create Date: 2023-08-09 18:17:12.204904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506520e7e4b4'
down_revision = 'fc1120bdb66f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
