"""Migration

Revision ID: 5129caaf3c54
Revises: 11547c28cbf9
Create Date: 2023-08-20 13:42:22.478407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5129caaf3c54'
down_revision = '11547c28cbf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
