"""Add Favourites table

Revision ID: 572769595647
Revises: c0055ec6b201
Create Date: 2023-07-23 02:47:05.183201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572769595647'
down_revision = 'c0055ec6b201'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favourites_id'), 'favourites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favourites_id'), table_name='favourites')
    op.drop_table('favourites')
    # ### end Alembic commands ###
