"""Migration

Revision ID: 5b49dfa852ce
Revises: f7826161a371
Create Date: 2023-08-09 18:15:59.101816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b49dfa852ce'
down_revision = 'f7826161a371'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
