"""Update username to complaint

Revision ID: 5d3e5b98bc94
Revises: b85983528589
Create Date: 2023-07-05 00:20:28.596586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3e5b98bc94'
down_revision = 'b85983528589'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('username', sa.String(), nullable=True))
    op.drop_constraint('complaints_user_fkey', 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'users', ['username'], ['username'], ondelete='cascade')
    op.drop_column('complaints', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key('complaints_user_fkey', 'complaints', 'users', ['user'], ['id'], ondelete='CASCADE')
    op.drop_column('complaints', 'username')
    # ### end Alembic commands ###
