"""Migration

Revision ID: 5d760450d41d
Revises: 9d1bb2537a85
Create Date: 2023-08-08 21:05:46.784257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d760450d41d'
down_revision = '9d1bb2537a85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
