"""Migration

Revision ID: 606e810e71c7
Revises: 65b781fa46f8
Create Date: 2023-08-18 19:13:34.279070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606e810e71c7'
down_revision = '65b781fa46f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
