"""Migration

Revision ID: 608cbe0faf9f
Revises: c2da8c5f231e
Create Date: 2023-08-11 19:03:36.524553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608cbe0faf9f'
down_revision = 'c2da8c5f231e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
