"""Test db

Revision ID: 614aefe09543
Revises: 12d1a51b8e19
Create Date: 2023-08-01 23:27:07.944281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614aefe09543'
down_revision = '12d1a51b8e19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
