"""Migration

Revision ID: 6344e0f12d46
Revises: d0eecbde58cc
Create Date: 2023-08-11 19:02:51.890184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6344e0f12d46'
down_revision = 'd0eecbde58cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
