"""Migration

Revision ID: 63f3d62fe954
Revises: 69c157a922fa
Create Date: 2023-08-11 19:07:24.233889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f3d62fe954'
down_revision = '69c157a922fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
