"""Migration

Revision ID: 658dc7194e53
Revises: f731b05b7f20
Create Date: 2023-08-11 17:45:05.767004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658dc7194e53'
down_revision = 'f731b05b7f20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
