"""Migration

Revision ID: 65b781fa46f8
Revises: 43b9fa926a71
Create Date: 2023-08-18 19:13:15.398044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b781fa46f8'
down_revision = '43b9fa926a71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
