"""Test db

Revision ID: 66a3eb0be668
Revises: 1c5159b8cf8b
Create Date: 2023-08-01 23:31:11.450438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a3eb0be668'
down_revision = '1c5159b8cf8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
