"""Migration

Revision ID: 67e6fef9c1f2
Revises: 0e527153bf41
Create Date: 2023-08-18 19:11:55.622342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e6fef9c1f2'
down_revision = '0e527153bf41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
