"""Migration

Revision ID: 69c157a922fa
Revises: 4605e07e7ad6
Create Date: 2023-08-11 19:07:00.485457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c157a922fa'
down_revision = '4605e07e7ad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
