"""Migration

Revision ID: 69fdfe9baca9
Revises: 5d760450d41d
Create Date: 2023-08-09 18:14:06.230760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fdfe9baca9'
down_revision = '5d760450d41d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
