"""Migration

Revision ID: 6a7ff2160902
Revises: b2b7afc5e405
Create Date: 2023-08-09 20:34:47.169140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7ff2160902'
down_revision = 'b2b7afc5e405'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
