"""Migration

Revision ID: 6b7aef8bfdea
Revises: cc6ce4e8bd1b
Create Date: 2023-08-12 18:29:14.561999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7aef8bfdea'
down_revision = 'cc6ce4e8bd1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
