"""Migration

Revision ID: 717830e5cdb1
Revises: 8ee25cb27713
Create Date: 2023-08-09 19:09:32.303481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717830e5cdb1'
down_revision = '8ee25cb27713'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
