"""Migration

Revision ID: 71e4cb4e88a1
Revises: 67e6fef9c1f2
Create Date: 2023-08-18 19:12:15.449942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e4cb4e88a1'
down_revision = '67e6fef9c1f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
