"""Migration

Revision ID: 75ad7443640d
Revises: 1126506b30ad
Create Date: 2023-08-08 20:33:20.023394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ad7443640d'
down_revision = '1126506b30ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
