"""Migration

Revision ID: 75ae732ea659
Revises: d2f5a9e2ad9b
Create Date: 2023-08-11 17:42:57.198800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ae732ea659'
down_revision = 'd2f5a9e2ad9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
