"""Migration

Revision ID: 78d96eea4e30
Revises: c0981972e778
Create Date: 2023-08-18 18:10:13.839659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d96eea4e30'
down_revision = 'c0981972e778'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
