"""Migration

Revision ID: 7a7b2e2eaf7d
Revises: 95ba48c28934
Create Date: 2023-08-08 18:16:44.467468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7b2e2eaf7d'
down_revision = '95ba48c28934'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
