"""Migration

Revision ID: 7c81acdf07dd
Revises: 71e4cb4e88a1
Create Date: 2023-08-18 19:12:35.563246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c81acdf07dd'
down_revision = '71e4cb4e88a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
