"""Migration

Revision ID: 7ce91608ad7a
Revises: 9708fd309156
Create Date: 2023-08-18 19:16:44.209783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce91608ad7a'
down_revision = '9708fd309156'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
