"""Migration

Revision ID: 7ddfca2cbef2
Revises: 953c838879c8
Create Date: 2023-08-20 19:52:01.981111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddfca2cbef2'
down_revision = '953c838879c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
