"""Migration

Revision ID: 81ae4c6fbaae
Revises: faf211fcd663
Create Date: 2023-08-18 18:12:19.955231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ae4c6fbaae'
down_revision = 'faf211fcd663'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
