"""Add post table

Revision ID: 8506f2d6db04
Revises: 18f6dfe91d2c
Create Date: 2023-06-28 00:19:04.762018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8506f2d6db04'
down_revision = '18f6dfe91d2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
