"""Migration

Revision ID: 86f066c18561
Revises: 1982f97b12ca
Create Date: 2023-08-08 20:32:57.856302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f066c18561'
down_revision = '1982f97b12ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
