"""Migration

Revision ID: 8e0a04763a07
Revises: fbf651e237d7
Create Date: 2023-08-08 18:08:55.053935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0a04763a07'
down_revision = 'fbf651e237d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
