"""Test db

Revision ID: 8e63c3af39e0
Revises: c91801a828f9
Create Date: 2023-08-01 23:45:20.107728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e63c3af39e0'
down_revision = 'c91801a828f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
