"""Migration

Revision ID: 8f1a20125420
Revises: 5129caaf3c54
Create Date: 2023-08-20 13:42:51.017123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1a20125420'
down_revision = '5129caaf3c54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
