"""Migration

Revision ID: 9396d09d3f0b
Revises: 9d4d3f5f95cd
Create Date: 2023-08-18 19:15:21.444111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9396d09d3f0b'
down_revision = '9d4d3f5f95cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
