"""Migration

Revision ID: 93e7c8332403
Revises: 7741dc1de152
Create Date: 2023-08-12 19:45:04.723772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e7c8332403'
down_revision = '7741dc1de152'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
