"""Changing Enum to String

Revision ID: 945ce1270273
Revises: 472e901135aa
Create Date: 2023-07-08 00:55:11.399914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '945ce1270273'
down_revision = '472e901135aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'reason',
               existing_type=postgresql.ENUM('first', 'second', 'third', name='complaintenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'reason',
               existing_type=postgresql.ENUM('first', 'second', 'third', name='complaintenum'),
               nullable=True)
    # ### end Alembic commands ###
