"""Migration

Revision ID: 953c838879c8
Revises: dfe4505a95fa
Create Date: 2023-08-20 18:29:54.371689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953c838879c8'
down_revision = 'dfe4505a95fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
