"""Migration

Revision ID: 9857b0ae61f0
Revises: 29ee1cebf326
Create Date: 2023-08-18 18:11:43.809953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9857b0ae61f0'
down_revision = '29ee1cebf326'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
