"""Migration

Revision ID: 9b133ffd7934
Revises: ecdaf704b83a
Create Date: 2023-08-08 18:07:59.207427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b133ffd7934'
down_revision = 'ecdaf704b83a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
