"""Migration

Revision ID: 9b7d274a40c3
Revises: c0ba34d29c77
Create Date: 2023-08-09 18:16:33.055657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7d274a40c3'
down_revision = 'c0ba34d29c77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
