"""Migration

Revision ID: 9d1bb2537a85
Revises: 0b0dfd832351
Create Date: 2023-08-08 21:04:44.725877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1bb2537a85'
down_revision = '0b0dfd832351'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
