"""Migration

Revision ID: 9d4d3f5f95cd
Revises: bcb61d040725
Create Date: 2023-08-18 19:14:55.471244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4d3f5f95cd'
down_revision = 'bcb61d040725'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
