"""Migration

Revision ID: 9e212eace932
Revises: a61f56fa949f
Create Date: 2023-08-18 18:45:28.292550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e212eace932'
down_revision = 'a61f56fa949f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
