"""Migration

Revision ID: 9ed20c8a0259
Revises: f9e4239cb533
Create Date: 2023-08-18 18:09:21.258297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed20c8a0259'
down_revision = 'f9e4239cb533'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
