"""Migration

Revision ID: a01e05e4a50d
Revises: 45195af5974f
Create Date: 2023-08-08 20:32:36.089811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01e05e4a50d'
down_revision = '45195af5974f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
