"""Migration

Revision ID: a0ce1234d8bb
Revises: ba225dd3b6a4
Create Date: 2023-08-18 19:14:14.744937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ce1234d8bb'
down_revision = 'ba225dd3b6a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
