"""Migration

Revision ID: a3cdaf99693d
Revises: b9455570372f
Create Date: 2023-08-09 20:35:21.899493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cdaf99693d'
down_revision = 'b9455570372f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
