"""Migration

Revision ID: a46968928a5f
Revises: a8bafcd377ac
Create Date: 2023-08-11 19:05:07.491213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46968928a5f'
down_revision = 'a8bafcd377ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
