"""Migration

Revision ID: a4c5b5e9151a
Revises: 93e7c8332403
Create Date: 2023-08-12 20:27:10.080219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c5b5e9151a'
down_revision = '93e7c8332403'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
