"""Migration

Revision ID: a61f56fa949f
Revises: e687ddf80c96
Create Date: 2023-08-18 18:35:00.666997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61f56fa949f'
down_revision = 'e687ddf80c96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
