"""Migration

Revision ID: a85a6523a699
Revises: 2481f5f3c047
Create Date: 2023-08-09 18:14:43.340463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85a6523a699'
down_revision = '2481f5f3c047'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
