"""Migration

Revision ID: a8a64f4975bf
Revises: 5bca44bdf855
Create Date: 2023-08-08 13:21:23.043473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a64f4975bf'
down_revision = '5bca44bdf855'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
