"""Migration

Revision ID: a8bafcd377ac
Revises: baae2dad6c4d
Create Date: 2023-08-11 19:04:44.581167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bafcd377ac'
down_revision = 'baae2dad6c4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
