"""Migration

Revision ID: a8cd28f6285e
Revises: 2abea64a8d31
Create Date: 2023-08-18 20:02:14.408387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cd28f6285e'
down_revision = '2abea64a8d31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
