"""Migration

Revision ID: aa8596920f21
Revises: 05e3e0ffed1b
Create Date: 2023-08-09 19:38:18.141135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8596920f21'
down_revision = '05e3e0ffed1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
