"""Migration

Revision ID: afab75f7ac52
Revises: d12d4150be03
Create Date: 2023-08-18 17:57:18.331293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afab75f7ac52'
down_revision = 'd12d4150be03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
