"""Add complaint

Revision ID: b18959076ca3
Revises: dff42f2136fa
Create Date: 2023-07-04 23:32:58.311375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18959076ca3'
down_revision = 'dff42f2136fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
