"""Migration

Revision ID: b2b7afc5e405
Revises: 49b48b8fbc02
Create Date: 2023-08-09 20:34:30.931531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b7afc5e405'
down_revision = '49b48b8fbc02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
