"""Migration

Revision ID: b419722428ff
Revises: 9b133ffd7934
Create Date: 2023-08-08 18:08:08.917730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b419722428ff'
down_revision = '9b133ffd7934'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
