"""Migration

Revision ID: b5789fb7fdcd
Revises: 81ae4c6fbaae
Create Date: 2023-08-18 18:12:39.208353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5789fb7fdcd'
down_revision = '81ae4c6fbaae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
