"""Add complaint

Revision ID: b85983528589
Revises: dc7c0c700c07
Create Date: 2023-07-04 23:40:46.549795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85983528589'
down_revision = 'dc7c0c700c07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint('complaints_post_id_fkey', 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'users', ['user'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'complaints', 'posts', ['post_id'], ['id'], ondelete='cascade')
    op.drop_constraint('posts_author_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author'], ['username'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_author_fkey', 'posts', 'users', ['author'], ['username'])
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key('complaints_post_id_fkey', 'complaints', 'posts', ['post_id'], ['id'])
    op.drop_column('complaints', 'user')
    # ### end Alembic commands ###
