"""Migration

Revision ID: b9455570372f
Revises: 6a7ff2160902
Create Date: 2023-08-09 20:35:04.600772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9455570372f'
down_revision = '6a7ff2160902'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
