"""Migration

Revision ID: baae2dad6c4d
Revises: 10b7bd2ecaeb
Create Date: 2023-08-11 19:04:21.823512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baae2dad6c4d'
down_revision = '10b7bd2ecaeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
