"""Migration

Revision ID: bcb61d040725
Revises: a0ce1234d8bb
Create Date: 2023-08-18 19:14:33.819661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb61d040725'
down_revision = 'a0ce1234d8bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
