"""Migration

Revision ID: be4881b23bb7
Revises: 5ad45418632b
Create Date: 2023-08-18 18:11:07.220267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4881b23bb7'
down_revision = '5ad45418632b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
