"""Add UC to Complaint on Comment Table

Revision ID: c0055ec6b201
Revises: 09c0717a6c22
Create Date: 2023-07-21 01:41:36.717768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0055ec6b201'
down_revision = '09c0717a6c22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('comment_user_complaint_uc', 'complaint_comment', ['comment_id', 'user'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_user_complaint_uc', 'complaint_comment', type_='unique')
    # ### end Alembic commands ###
