"""Migration

Revision ID: c0ba34d29c77
Revises: 5b49dfa852ce
Create Date: 2023-08-09 18:16:15.913175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ba34d29c77'
down_revision = '5b49dfa852ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
