"""Migration

Revision ID: c0c0e5845529
Revises: dc1ec67d1e6c
Create Date: 2023-08-08 21:04:10.542797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c0e5845529'
down_revision = 'dc1ec67d1e6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
