"""Migration

Revision ID: c2da8c5f231e
Revises: 6344e0f12d46
Create Date: 2023-08-11 19:03:12.776141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2da8c5f231e'
down_revision = '6344e0f12d46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
