"""Migration

Revision ID: c32e6c822eaa
Revises: 41dd939c7a7c
Create Date: 2023-08-09 20:56:00.802799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32e6c822eaa'
down_revision = '41dd939c7a7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
