"""Migration

Revision ID: c512f34e5ce6
Revises: cca17ab78a83
Create Date: 2023-08-11 15:47:56.979231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c512f34e5ce6'
down_revision = 'cca17ab78a83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
