"""Migration

Revision ID: c6a46fc0a46d
Revises: 41f40569a336
Create Date: 2023-08-09 18:15:20.748366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a46fc0a46d'
down_revision = '41f40569a336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
