"""Add UC to Complaints

Revision ID: c87511b9ff7c
Revises: abe458135e86
Create Date: 2023-07-09 22:35:51.887975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87511b9ff7c'
down_revision = 'abe458135e86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_user_complaint_uc', 'complaints', ['post_id', 'user'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_user_complaint_uc', 'complaints', type_='unique')
    # ### end Alembic commands ###
