"""Migration

Revision ID: ca55c14dd6a1
Revises: cc225c19dc97
Create Date: 2023-08-11 17:43:36.280009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca55c14dd6a1'
down_revision = 'cc225c19dc97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
