"""Migration

Revision ID: cc225c19dc97
Revises: 75ae732ea659
Create Date: 2023-08-11 17:43:15.972666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc225c19dc97'
down_revision = '75ae732ea659'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
