"""Migration

Revision ID: cc6ce4e8bd1b
Revises: 445239fdfa44
Create Date: 2023-08-12 18:07:29.186010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6ce4e8bd1b'
down_revision = '445239fdfa44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
