"""Migration

Revision ID: cca17ab78a83
Revises: c32e6c822eaa
Create Date: 2023-08-09 21:06:05.442513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca17ab78a83'
down_revision = 'c32e6c822eaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
