"""Migration

Revision ID: cd0775648dcf
Revises: c0c0e5845529
Create Date: 2023-08-08 21:04:21.877314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0775648dcf'
down_revision = 'c0c0e5845529'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
