"""Migration

Revision ID: d032137bf9f4
Revises: a8a64f4975bf
Create Date: 2023-08-08 13:53:15.588107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd032137bf9f4'
down_revision = 'a8a64f4975bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
