"""Migration

Revision ID: d0eecbde58cc
Revises: f25eded6729a
Create Date: 2023-08-11 17:47:10.077276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0eecbde58cc'
down_revision = 'f25eded6729a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
