"""Migration

Revision ID: d12d4150be03
Revises: fbc1ce078165
Create Date: 2023-08-18 17:18:10.040457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12d4150be03'
down_revision = 'fbc1ce078165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
