"""Migration

Revision ID: d2f5a9e2ad9b
Revises: 3778b6c52813
Create Date: 2023-08-11 17:42:36.783490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f5a9e2ad9b'
down_revision = '3778b6c52813'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
