"""Migration

Revision ID: d30301b66dea
Revises: e772b3c9b79f
Create Date: 2023-08-18 19:02:53.740450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30301b66dea'
down_revision = 'e772b3c9b79f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
