"""Migration

Revision ID: d91265e6e811
Revises: 9ed20c8a0259
Create Date: 2023-08-18 18:09:38.379153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91265e6e811'
down_revision = '9ed20c8a0259'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
