"""Migration

Revision ID: dc1ec67d1e6c
Revises: 45a7a29cc863
Create Date: 2023-08-08 20:34:00.174244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1ec67d1e6c'
down_revision = '45a7a29cc863'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
