"""Migration

Revision ID: dc3e62c2eb11
Revises: e72f2dcea522
Create Date: 2023-08-12 21:02:18.888422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3e62c2eb11'
down_revision = 'e72f2dcea522'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
