"""Add complaint

Revision ID: dc7c0c700c07
Revises: 6d0715a2956d
Create Date: 2023-07-04 23:33:55.402481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7c0c700c07'
down_revision = '6d0715a2956d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
