"""Migration

Revision ID: dfe4505a95fa
Revises: 1747cb5ca659
Create Date: 2023-08-20 13:43:57.557445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe4505a95fa'
down_revision = '1747cb5ca659'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
