"""Add complaint

Revision ID: dff42f2136fa
Revises: e0f8522bce7d
Create Date: 2023-07-04 23:29:13.868975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff42f2136fa'
down_revision = 'e0f8522bce7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
