"""Migration

Revision ID: e687ddf80c96
Revises: ec6a00c39dfb
Create Date: 2023-08-18 18:13:45.890229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e687ddf80c96'
down_revision = 'ec6a00c39dfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
