"""Migration

Revision ID: e6f606396f24
Revises: ed7bb791a863
Create Date: 2023-08-11 19:08:11.119972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f606396f24'
down_revision = 'ed7bb791a863'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
