"""Migration

Revision ID: e72f2dcea522
Revises: a4c5b5e9151a
Create Date: 2023-08-12 20:52:53.342554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72f2dcea522'
down_revision = 'a4c5b5e9151a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
