"""Migration

Revision ID: e772b3c9b79f
Revises: 3475413e4f68
Create Date: 2023-08-18 18:46:35.982506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e772b3c9b79f'
down_revision = '3475413e4f68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
