"""Migration

Revision ID: e8a58a65dec2
Revises: dc3e62c2eb11
Create Date: 2023-08-15 14:29:58.299137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a58a65dec2'
down_revision = 'dc3e62c2eb11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
