"""Migration

Revision ID: e8ac5e8618a5
Revises: 04c7f9b1a34e
Create Date: 2023-08-11 19:10:44.802783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ac5e8618a5'
down_revision = '04c7f9b1a34e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
