"""Migration

Revision ID: ea6bc181f955
Revises: 783fb1a9a0f4
Create Date: 2023-08-05 19:43:02.970808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6bc181f955'
down_revision = '783fb1a9a0f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
