"""Migration

Revision ID: ec6a00c39dfb
Revises: 1a155e29faa9
Create Date: 2023-08-18 18:13:17.124209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6a00c39dfb'
down_revision = '1a155e29faa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
