"""Migration

Revision ID: ec9234d0b862
Revises: 8e0a04763a07
Create Date: 2023-08-08 18:09:05.623842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9234d0b862'
down_revision = '8e0a04763a07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
