"""Migration

Revision ID: ecdaf704b83a
Revises: d032137bf9f4
Create Date: 2023-08-08 18:07:49.467930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdaf704b83a'
down_revision = 'd032137bf9f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
