"""Migration

Revision ID: ed7bb791a863
Revises: 63f3d62fe954
Create Date: 2023-08-11 19:07:47.402773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7bb791a863'
down_revision = '63f3d62fe954'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
