"""Test db

Revision ID: ee01f6d1553b
Revises: 66a3eb0be668
Create Date: 2023-08-01 23:33:14.612716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee01f6d1553b'
down_revision = '66a3eb0be668'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
