"""Migration

Revision ID: f25eded6729a
Revises: f8149edef3ff
Create Date: 2023-08-11 17:46:47.624609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25eded6729a'
down_revision = 'f8149edef3ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
