"""Adding expires on commit

Revision ID: f391859603b1
Revises: f2f774b3e0e1
Create Date: 2023-07-18 02:05:06.357228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f391859603b1'
down_revision = 'f2f774b3e0e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
