"""Migration

Revision ID: f47b1990148d
Revises: 45fe6a1196af
Create Date: 2023-08-18 19:11:17.627129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47b1990148d'
down_revision = '45fe6a1196af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
