"""Migration

Revision ID: f7826161a371
Revises: c6a46fc0a46d
Create Date: 2023-08-09 18:15:39.042506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7826161a371'
down_revision = 'c6a46fc0a46d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
