"""Migration

Revision ID: f8149edef3ff
Revises: 52edc3b05f73
Create Date: 2023-08-11 17:46:25.852531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8149edef3ff'
down_revision = '52edc3b05f73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
