"""Migration

Revision ID: f9e4239cb533
Revises: afab75f7ac52
Create Date: 2023-08-18 18:09:03.446528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e4239cb533'
down_revision = 'afab75f7ac52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
