"""Migration

Revision ID: fa0869c6d860
Revises: 0dbe86680beb
Create Date: 2023-08-09 20:35:59.850796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0869c6d860'
down_revision = '0dbe86680beb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
