"""Migration

Revision ID: faf211fcd663
Revises: 9857b0ae61f0
Create Date: 2023-08-18 18:12:02.292041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf211fcd663'
down_revision = '9857b0ae61f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
