"""Migration

Revision ID: fb677d73b148
Revises: 9396d09d3f0b
Create Date: 2023-08-18 19:15:42.113781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb677d73b148'
down_revision = '9396d09d3f0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
