"""Migration

Revision ID: fbf651e237d7
Revises: 20d0373c1787
Create Date: 2023-08-08 18:08:41.225940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf651e237d7'
down_revision = '20d0373c1787'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
