"""Migration

Revision ID: fc1120bdb66f
Revises: 9b7d274a40c3
Create Date: 2023-08-09 18:16:49.232336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1120bdb66f'
down_revision = '9b7d274a40c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
