version: '3.8'

services:
  db:
    image:
      postgres:15-alpine
    restart:
      'on-failure'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - 5432
    networks:
      - anime_app_network

  app:
    build: .
    volumes:
      - .:/src
    restart:
      'always'
    ports:
      - 80
    command:
      sh -c 'alembic stamp head &&
             alembic revision --autogenerate -m "Migration" &&
             alembic upgrade head &&
             flake8 &&
             python -m anime_app.api'
    depends_on:
      - db
    networks:
      - anime_app_network

  nginx:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - anime_app_network

volumes:
  postgres_data:

networks:
  anime_app_network:
